name: 'Sync template repository'
description: 'Sync template repository'
inputs:
  repo_token:
    description: "Token to use for PR creation."
    required: true
  target_repository:
    description: "Repository to apply changes."
    required: true
  target_branch:
    description: "Branch to apply changes."
    default: "main"
    required: false
  base_branch:
    description: "Branch to use as base for PR creation."
    default: "main"
    required: false
  pr_branch_name:
    description: "Branch name to use for PR creation."
    default: "sync-template-repository"
    required: false
  include_patterns:
    description: "Space separated include glob patterns to sync. For security reasons, `.github/workflows` cannot be included."
    default: "**/*"
    required: false
  exclude_patterns:
    description: "Space separated exclude glob patterns to sync."
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
