name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all
  test1: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          target_repository: 'besna-institute/sync-template-repository'
          target_branch: 'test/target'
          base_branch: 'test/base'
          branch_name: 'sync-template-repository'
  test2: # Skip the action if the target branch is the same as the base branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          target_repository: 'besna-institute/sync-template-repository'
          target_branch: 'test/target-no-changes'
          base_branch: 'test/base'
          branch_name: 'sync-template-repository-no-changes'
